syntax = "proto3";

option csharp_namespace = "PaymentGateway.SyncContracts.Commission";

package synccommission;

service SyncCommissionService {
    rpc GetBankCommissions (PageRequest) returns (BankCommissionsPage);
    rpc GetMerchantCommissions (PageRequest) returns (MerchantCommissionsPage);
}

message PageRequest {
    int32 page = 1;
    int32 page_size = 2;
}

message BankCommissionItem {
    string bank_commission_id = 1;
    string bank_id = 2;
    int32 card_brand = 3;
    int32 card_type = 4;
    int32 transaction_region = 5;
    string rate = 6;
}

message BankCommissionsPage {
    repeated BankCommissionItem items = 1;
    bool has_next_page = 2;
}

message MerchantCommissionItem {
    string merchant_commission_id = 1;
    string merchant_id = 2;
    string bank_commission_id = 3;
    int32 card_brand = 4;
    int32 card_type = 5;
    int32 transaction_region = 6;
    string rate = 7;
}

message MerchantCommissionsPage {
    repeated MerchantCommissionItem items = 1;
    bool has_next_page = 2;
}